<a href="https://colab.research.google.com/github/a1coderxt/a1coderxt/blob/main/00__pytorch__fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [98]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


## Introduction to Tensors

## Creating tensors

Pytorch tensors are created using torch.tensor()

In [99]:
 scalar = torch.tensor(7)
 scalar

tensor(7)

In [100]:
scalar.ndim

0

In [101]:
scalar.item()

7

In [102]:
#vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [103]:
vector.ndim

1

In [104]:
vector.shape

torch.Size([2])

In [105]:
#matrix
MATRIX = torch.tensor([[7,8 ]
                       ,[6,4]])
MATRIX

tensor([[7, 8],
        [6, 4]])

In [106]:
MATRIX.ndim

2

In [107]:
MATRIX[0]

tensor([7, 8])

In [108]:
MATRIX[1]

tensor([6, 4])

In [109]:
MATRIX.shape

torch.Size([2, 2])

In [110]:
#Tensor
TENSOR = torch.tensor([[[12, 1,  13],
                        [18 , 19 , 7],
                        [14, 15 , 16]]])
TENSOR

tensor([[[12,  1, 13],
         [18, 19,  7],
         [14, 15, 16]]])

In [111]:
TENSOR.ndim

3

In [112]:
TENSOR.shape

torch.Size([1, 3, 3])

In [113]:
TENSOR[0]

tensor([[12,  1, 13],
        [18, 19,  7],
        [14, 15, 16]])

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> Look at data -> update random numbers -> look at data -> updatae random numbers`


In [114]:
#create a random tensor of size or shape (3, 4)

random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.7566, 0.2137, 0.0171, 0.3669],
        [0.2028, 0.7598, 0.6500, 0.9582],
        [0.3157, 0.1012, 0.1297, 0.6918]])

In [115]:
random_tensor.ndim

2

In [116]:
#Create a random tensor with similar  shape to an image tensor

random_image = torch.rand(size=(224 , 224 ,3))  # height , width , color channels(rgb)
random_image.shape , random_image.ndim



(torch.Size([224, 224, 3]), 3)

In [117]:
random_my_data = torch.rand(30, 2)

In [118]:
random_my_data.shape , random_my_data.ndim

(torch.Size([30, 2]), 2)

### Zero and ones

In [119]:
#creating a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [120]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [121]:
#cerating tensor of ones

ones = torch.ones(size=(4,5))
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

###Creating a range of tensors and tensors like

Instead of using range() use arange()


In [122]:
#Use torch.arange()
one_to_ten = torch.arange(start= 1, end = 11 , step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [123]:
#Crating tensor like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [124]:
fake_range = torch.arange(start=1 , end=51 ,step=2)
fake_range

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35,
        37, 39, 41, 43, 45, 47, 49])

In [125]:
fake_zeros = torch.zeros_like(fake_range)
fake_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0])

### Tensor Datatypes

**Note:** Tensor datatype is one of the 3 big errors you'll run into with Pytorch & deep learning:

1. Tensors not right datatypes
2. Tensors not right shape
3. Tensors not on the right device

Precision in computing

In [126]:
#float 32 tensor

float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, #what datatypes is the tensor
                               device=None, # what evice is your tensor on
                               requires_grad=False) #whether or not to track gradients
float_32_tensor

tensor([3., 6., 9.])

In [127]:
float_32_tensor.dtype

torch.float32

In [128]:
#this is how we convert the datatype

float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [129]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [130]:
int_32_tensor = torch.tensor([2, 4, 8] , dtype=torch.int32)
int_32_tensor

tensor([2, 4, 8], dtype=torch.int32)

In [131]:
float_32_tensor * int_32_tensor

tensor([ 6., 24., 72.])

### Getting info from tensors ,tensor attribues


1. Tensors not right datatypes - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a device, can use `tensor.device`

In [132]:
#Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.5096, 0.8646, 0.7665, 0.8365],
        [0.2745, 0.5108, 0.3933, 0.5372],
        [0.3117, 0.9028, 0.4423, 0.8562]])

In [133]:
#find out details about some tensor

print(some_tensor)
print(f'DataType of tensor : {some_tensor.dtype}')
print(f'Shape of tensor : {some_tensor.shape}')
print(f'Device tensor is on : {some_tensor.device}')

tensor([[0.5096, 0.8646, 0.7665, 0.8365],
        [0.2745, 0.5108, 0.3933, 0.5372],
        [0.3117, 0.9028, 0.4423, 0.8562]])
DataType of tensor : torch.float32
Shape of tensor : torch.Size([3, 4])
Device tensor is on : cpu


### Manipulating tensors (tensor operation)

Tensor Operation Inculdes.

1. Additon
2. Subtraction
3. Multiplication (element-wise)
4. Division
5. Matrix Multiplication

In [134]:
#Create a tensor and add 10

tensor = torch.tensor([1 ,2 ,3])
tensor + 10

# or we can write like this too
# tensor.add(tensor , 10)

tensor([11, 12, 13])

In [135]:
#multiply tensor by 10
tensor * 10

# or we can write like this too
# tensor.mul(tensor , 10)

tensor([10, 20, 30])

In [136]:
#Subtract tensor by 10
tensor - 10

tensor([-9, -8, -7])

In [137]:
#Division tensor by 10
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

 ### Matrix Multiplication
Two main way of doing this
 1.Element wise
 2.Matrix multiplication


There are tow main rules that performing matrix multiplication needs to satisfy:

1. The **inner Dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work

2. The resulting matrix has the shape of the **outer dimensions**:

* `(2, 3) @ (3, 2)`  -> `(2, 2)`
* `(3, 2) @ (2, 3)`  -> `(3, 3)`
*

In [138]:

torch.matmul(torch.rand(3, 2) , torch.rand(2, 3))



tensor([[0.4961, 0.2033, 0.3663],
        [0.5695, 0.2429, 0.4022],
        [0.0386, 0.0161, 0.0280]])

In [139]:

# 1. Element wise

print(tensor, "*" , tensor )
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [140]:
# 2. Matrix Multiplication and this the best and ideal way of doing it
torch.matmul(tensor, tensor)


tensor(14)

In [141]:
# we can do matrix multiplication by for loop but its not ideal use matmul() instead

value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)


tensor(14)


### One of the most common errors in deep learning: shape error

In [143]:
#shape for matrix multiplication

tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 8],
                         [9, 10],
                         [11, 12]])


mat_multi = torch.matmul(tensor_A , tensor_B)
print(f"Matrix Multiplication is : {mat_multi}")

#Here the problem is we are not matching the inner dimensions

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [157]:
tensor_A.shape , tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues , we can manipulate the shape of one of our tensor using a **transpose**.

A **Transpose** switches the axes or dimensions of given tensor

In [158]:
tensor_B.T

tensor([[ 7,  9, 11],
        [ 8, 10, 12]])

In [159]:
tensor_B.T.shape

torch.Size([2, 3])

In [160]:
# The Matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes : tensor_A = {tensor_A.shape} , tensor_B = {tensor_B.shape}")
print(f"New shapes : tensor_A = {tensor_A.shape} , tensor_B.T  = {tensor_B.T.shape}")


mat_multi = torch.matmul(tensor_A , tensor_B.T)
print(f"Matrix Multiplication is : \n {mat_multi}")
mat_multi.shape

Original shapes : tensor_A = torch.Size([3, 2]) , tensor_B = torch.Size([3, 2])
New shapes : tensor_A = torch.Size([3, 2]) , tensor_B.T  = torch.Size([2, 3])
Matrix Multiplication is : 
 tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])


torch.Size([3, 3])

## Finding the min , max , mean , sum , etc(tensor aggregation)
and these are methods ()

In [161]:
#Create a tensor
x = torch.arange(0 , 100 , 10)
x , x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [162]:
torch.min(x) , x.min()

(tensor(0), tensor(0))

In [163]:
torch.max(x) , x.max()

(tensor(90), tensor(90))

In [164]:
# find the mean
# torch.mean(x)  , x.mean() ->>>  won't work on long datatype it require float datatype

torch.mean(x.type(torch.float32))

tensor(45.)

In [165]:
torch.sum(x) , x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max

In [166]:
#Find the posion is the tensor which have minimum value index
x.argmin()

tensor(0)

In [168]:
#Finding the position in the tensor which have maximum value index
x.argmax()


tensor(9)

## Reshaping , stacking , squeezing and unsqueezing tensor

* Reshapin - reshape an input tensor to a defined shape

* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - Combine multiple tensor on top  of each other (vstack) or side by side (hstack)
* Squeeze - remove all `1` Dimensions from a tensor
* Unsqueeze - add a `1` dimensions to a target tensor
* permute - Return a view of the input with the dimensions permuted(swapped) in a certain way

In [169]:
# Lets creat a tensor
x = torch.arange(1. ,10.)

x ,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [170]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped , x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [171]:
# Change the view >> it shares the memory

z = x.view(1,9)
z , z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [172]:
# changing z changes x (because of a tensor shares the same memory as the original input)

z[: , 0] =5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [173]:
# Stack tensors on top of each other

x_stacked = torch.stack([x, x , x , x] , dim=0)
x_stacked


tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [179]:
# Squeezing the tensor -> it removes all the single dimension
print(f"Preious tensor :  {x_reshaped} ")
print(f"Previous shape :  {x_reshaped.shape} ")

#Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor :  {x_squeezed} ")
print(f"New shape : {x_squeezed.shape} ")
# so you can see it removed the single dimension

Preious tensor :  tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]) 
Previous shape :  torch.Size([1, 9]) 

New tensor :  tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]) 
New shape : torch.Size([9]) 


In [186]:
# torch.unqueeze - > adds an single dimension to a target tensor at specific dim

print(f"Previous target : {x_squeezed}")
print(f"Previous shape : {x_squeezed.shape}")

# Add an extra dimension with  unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"New Target : {x_unsqueezed}" )
print(f"New shape : {x_unsqueezed.shape}")


Previous target : tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape : torch.Size([9])
New Target : tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape : torch.Size([1, 9])


In [187]:
# torch.permute - rearranges the dimension of target of a target tensor in specified order
#mostly used in images

x_original = torch.rand(size=(224 , 244 , 3)) # height , width , color_channels

#permute the original tensor to reaarange the axis or dim order

x_permuted = x_original.permute(2, 0, 1) # shafts axis 0->1 , 1->2 , 2->0

print(f"Previous Shape: {x_original.shape} ")
print(f"New Shape: {x_permuted.shape} ") # [color_channels , height , width]

Previous Shape: torch.Size([224, 244, 3]) 
New Shape: torch.Size([3, 224, 244]) 


In [188]:
x_original[0, 0, 0] = 12123
x_original[0, 0, 0] , x_permuted[0, 0, 0]

(tensor(12123.), tensor(12123.))

## Indexing (selecting data from tensor)

Indexing with pytorch is similar to indexing with NumPy

In [189]:
#create a tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [191]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [192]:
#Lets index on middle bracket
x[0][0]

tensor([1, 2, 3])

In [197]:
# Lets index on most inner or last dim
x[0][2][2]  # [inner][row][column]

tensor(9)

## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing Library.

and becayse if this, Pytorch has Functionality to interact with it.

* Data in NumPy , want in Pytorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> torch.tensor.numpy()

In [201]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0 , 8.0)
tensor = torch.from_numpy(array) # when converting from numpy to pytorch , pytorch reflects numpy's default datatype of float64 unless specified otherwise
array , tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [203]:
# change the value of array , what it will do with tensor?
array = array + 1
array , tensor
# we can see it do not chnage the value of tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [205]:
#Tensor to NumPy array
tensor = torch.ones(7)

numpy_tensor = tensor.numpy()
tensor , numpy_tensor


(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [207]:
# Change the tensor , what happens to numpy_tensor
tensor = tensor + 2
tensor,  numpy_tensor
# we can see it do not affects the numpy_tensor

(tensor([3., 3., 3., 3., 3., 3., 3.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)
In short how a neural network learns :

`Start with random numbers -> tensor opererations  -> update random numbes to try and make them better of the data -> again.. -> again.. and -> again..`

To reduce the randomness in neural networks and pytorch comes the conceps of **random seed.**

Essentially what the random seed does is "flavour" the randomness

In [219]:
random_tensor_A = torch.rand(3, 2)
random_tensor_B = torch.rand(3, 2)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)


tensor([[0.3864, 0.1083],
        [0.3181, 0.8110],
        [0.3771, 0.2956]])
tensor([[0.9609, 0.8860],
        [0.9173, 0.0012],
        [0.0480, 0.0764]])
tensor([[False, False],
        [False, False],
        [False, False]])


In [226]:
# Now lets make some random but reproducible tensors

#set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 2)


torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 2)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150],
        [0.3829, 0.9593],
        [0.3904, 0.6009]])
tensor([[0.8823, 0.9150],
        [0.3829, 0.9593],
        [0.3904, 0.6009]])
tensor([[True, True],
        [True, True],
        [True, True]])
